spring:
  profiles: default
  application:
    name: homeboy
  datasource:
    url: postgres://hdhbnuiexygjut:35f9fd141ee84153208c5253bd5231091b06c39a303079b011847ff2e3beeebd@ec2-107-20-214-99.compute-1.amazonaws.com:5432/deemb2scn20hb8
    username: hdhbnuiexygjut
    password: 35f9fd141ee84153208c5253bd5231091b06c39a303079b011847ff2e3beeebd
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    tomcat:
      max-active: 10
      max-wait: 10000
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1;
  jpa:
    hibernate.ddl-auto: update

---
spring:
  profiles: development
  application:
    name: homeboy
  datasource:
    url: jdbc:mysql://mysql/homeboy
    username: root
    password: root
    driverClassName:
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    tomcat:
      max-active: 10
      max-wait: 10000
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1;
  jpa:
    hibernate.ddl-auto: update