spring:
  profiles: default
  application:
    name: homeboy
  datasource:
    url: xxxxx
    username: xxx
    password: xxx
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    tomcat:
      max-active: 10
      max-wait: 10000
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1;
  jpa:
    hibernate.ddl-auto: update